const RequestActionTypes = {
    FETCH_REQUESTS_START: "FETCH_REQUESTS_START",
    FETCH_REQUESTS_SUCCESS: "FETCH_REQUESTS_SUCCESS",
    FETCH_REQUESTS_FAIL: "FETCH_REQUESTS_FAIL",
    ACCEPT_REQUEST_START: "ACCEPT_REQUEST_START",
    ACCEPT_REQUEST_SUCCESS: "ACCEPT_REQUEST_SUCCESS",
    ACCEPT_REQUEST_FAIL: "ACCEPT_REQUEST_FAIL",
    CANCEL_REQUEST_START: "CANCEL_REQUEST_START",
    CANCEL_REQUEST_SUCCESS: "CANCEL_REQUEST_SUCCESS",
    CANCEL_REQUEST_FAIL: "CANCEL_REQUEST_FAIL",
    PICKED_PATIENT_START: "PICKED_PATIENT_START",
    PICKED_PATIENT_SUCCESS: "PICKED_PATIENT_SUCCESS",
    PICKED_PATIENT_FAIL: "PICKED_PATIENT_FAIL",
    FINISH_REQUEST_START: "FINISH_REQUEST_START",
    FINISH_REQUEST_SUCCESS: "FINISH_REQUEST_SUCCESS",
    FINISH_REQUEST_FAIL: "FINISH_REQUEST_FAIL",
    CLEAR_REQUEST: "CLEAR_REQUEST",
    FETCH_SYSTEM_CONFIG_START: "FETCH_SYSTEM_CONFIG_START",
    FETCH_SYSTEM_CONFIG_SUCCESS: "FETCH_SYSTEM_CONFIG_SUCCESS",
    FETCH_SYSTEM_CONFIG_FAIL: "FETCH_SYSTEM_CONFIG_FAIL",
    REJECT_REQUEST_START: "REJECT_REQUEST_START",
    REJECT_REQUEST_SUCCESS: "REJECT_REQUEST_SUCCESS",
    REJECT_REQUEST_FAIL: "REJECT_REQUEST_FAIL",
    REMOVE_REQUESTS: "REMOVE_REQUESTS"
};

export default RequestActionTypes;
