const RequestActionTypes = {
    FETCH_REQUEST_START: "FETCH_REQUEST_START",
    FETCH_REQUEST_SUCCESS: "FETCH_REQUEST_SUCCESS",
    FETCH_REQUEST_FAIL: "FETCH_REQUEST_FAIL",
    ACCEPT_REQUEST_START: "ACCEPT_REQUEST_START",
    ACCEPT_REQUEST_SUCCESS: "ACCEPT_REQUEST_SUCCESS",
    ACCEPT_REQUEST_FAIL: "ACCEPT_REQUEST_FAIL",
    CANCEL_REQUEST_START: "CANCEL_REQUEST_START",
    CANCEL_REQUEST_SUCCESS: "CANCEL_REQUEST_SUCCESS",
    CANCEL_REQUEST_FAIL: "CANCEL_REQUEST_FAIL",
    PICKED_PATIENT_START: "PICKED_PATIENT_START",
    PICKED_PATIENT_SUCCESS: "PICKED_PATIENT_SUCCESS",
    PICKED_PATIENT_FAIL: "PICKED_PATIENT_FAIL",
    FINISH_REQUEST_START: "FINISH_REQUEST_START",
    FINISH_REQUEST_SUCCESS: "FINISH_REQUEST_SUCCESS",
    FINISH_REQUEST_FAIL: "FINISH_REQUEST_FAIL",
    CLEAR_REQUEST: "CLEAR_REQUEST",
    VIEW_HISTORY: "VIEW_HISTORY"
};

export default RequestActionTypes;
