const AmbulanceActionTypes = {
    FETCH_AMBULANCE_START: "FETCH_AMBULANCE_START",
    FETCH_AMBULANCE_SUCCESS: "FETCH_AMBULANCE_SUCCESS",
    FETCH_AMBULANCE_FAIL: "FETCH_AMBULANCE_FAIL",
    REGISTER_AMBULANCE_START: "REGISTER_AMBULANCE_START",
    REGISTER_AMBULANCE_SUCCESS: "REGISTER_AMBULANCE_SUCCESS",
    REGISTER_AMBULANCE_FAIL: "REGISTER_AMBULANCE_FAIL",
    UPDATE_AMBULANCE_START: "UPDATE_AMBULANCE_START",
    UPDATE_AMBULANCE_SUCCESS: "UPDATE_AMBULANCE_SUCCESS",
    UPDATE_AMBULANCE_FAIL: "UPDATE_AMBULANCE_FAIL",
    GET_AMBULANCE_NOTE_START: "GET_AMBULANCE_NOTE_START",
    GET_AMBULANCE_NOTE_SUCCESS: "GET_AMBULANCE_NOTE_SUCCESS",
    GET_AMBULANCE_NOTE_FAIL: "GET_AMBULANCE_NOTE_FAIL",
    UNREGISTER_AMBULANCE_START: "UNREGISTER_AMBULANCE_START",
    UNREGISTER_AMBULANCE_SUCCESS: "UNREGISTER_AMBULANCE_SUCCESS",
    UNREGISTER_AMBULANCE_FAIL: "UNREGISTER_AMBULANCE_FAIL",
    CLEAR_AMBULANCE_NOTE: "CLEAR_AMBULANCE_NOTE"
};

export default AmbulanceActionTypes;
