const AmbulanceActionTypes = {
    FETCH_AMBULANCE_START: "FETCH_AMBULANCE_START",
    FETCH_AMBULANCE_SUCCESS: "FETCH_AMBULANCE_SUCCESS",
    FETCH_AMBULANCE_FAIL: "FETCH_AMBULANCE_FAIL",
    REGISTER_AMBULANCE_START: "REGISTER_AMBULANCE_START",
    REGISTER_AMBULANCE_SUCCESS: "REGISTER_AMBULANCE_SUCCESS",
    REGISTER_AMBULANCE_FAIL: "REGISTER_AMBULANCE_FAIL",
    UPDATE_AMBULANCE_START: "UPDATE_AMBULANCE_START",
    UPDATE_AMBULANCE_SUCCESS: "UPDATE_AMBULANCE_SUCCESS",
    UPDATE_AMBULANCE_FAIL: "UPDATE_AMBULANCE_FAIL"
};

export default AmbulanceActionTypes;
