const AmbulanceActionTypes = {
    REGISTER_AMBULANCE_START: "REGISTER_AMBULANCE_START",
    REGISTER_AMBULANCE_SUCCESS: "REGISTER_AMBULANCE_SUCCESS",
    REGISTER_AMBULANCE_FAIL: "REGISTER_AMBULANCE_FAIL",
    UPDATE_AMBULANCE_START: "UPDATE_AMBULANCE_START",
    UPDATE_AMBULANCE_SUCCESS: "UPDATE_AMBULANCE_SUCCESS",
    UPDATE_AMBULANCE_FAIL: "UPDATE_AMBULANCE_FAIL"
};

export default AmbulanceActionTypes;
