const UserActionTypes = {
    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL: "SIGN_IN_FAIL",
    UPDATE_CONFIRMING_STATUS: "UPDATE_CONFIRMING_STATUS",
    HANDLE_APPROVED_REGISTER_AMBULANCE: "HANDLE_APPROVED_REGISTER_AMBULANCE",
    LOGOUT: "LOGOUT",
    HANDLE_UNREGISTER_AMBULANCE: "HANDLE_UNREGISTER_AMBULANCE",
    HANDLE_UPDATE_AMBULANCE: "HANDLE_UPDATE_AMBULANCE",
    UPDATE_USER_START: "UPDATE_USER_START",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAIL: "UPDATE_USER_FAIL",
    UPDATE_SETTING_START: "UPDATE_SETTING_START",
    UPDATE_SETTING_SUCCESS: "UPDATE_SETTING_SUCCESS",
    UPDATE_SETTING_FAIL: "UPDATE_SETTING_FAIL"
};

export default UserActionTypes;
