const UserActionTypes = {
    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAIL: "SIGN_IN_FAIL",
    UPDATE_CONFIRMING_STATUS: "UPDATE_CONFIRMING_STATUS",
    HANDLE_APPROVED_REGISTER_AMBULANCE: "HANDLE_APPROVED_REGISTER_AMBULANCE",
    LOGOUT: "LOGOUT"
};

export default UserActionTypes;
